### ISSUE TITLE
Wizard in vertical mode does not render correctly 

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#1615]
**Bug**

The wizard requires css that is not included in the widget itself, this does not present itself on parade as parade includes the css:

```css
*, :after, :before {
    box-sizing: border-box;
}
```

Without this css the lines between the steps render incorrectly:

<img width="277" alt="examples" src="https://user-images.githubusercontent.com/1982678/101877774-73d61b00-3b86-11eb-9c82-6be95371bb11.png">
