### ISSUE TITLE
"Extending" Themes

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#277]
**User Story**

As a developer, I need a clear pattern for _extending_ themes, taking an existing theme and adding additional widget classes, additional styles to widgets, and potentially _overriding_ some of the theme styles.

**Specific Use Case**

I have a corporate theme which has been provided.  Our project requires that we add/adjust some of the styles for our project, therefore I need to extend that base theme.  I do not expect to utilise `!important` to achieve this.

**Comment by tomdye** [comment]
I believe that in this situation you would take the `corporate` theme as a `base`. In your new theme you would re-export the parts of the base theme that you want to use `as-is` and would utilise `compose` to customise and change the theme for particular components.

**example**

```typescript
/* base/theme.ts */
import * as textInput from './textInput.m.css';
import * as button from './button.m.css';

export default {
   textInput,
   button
};
```

```typescript
/* custom/theme.ts */
import * as textInput from '../base/textInput.m.css'; // use base textInput theme
import * as button from './button.m.css'; // use custom button style

export default {
   textInput,
   button
};
```

```css
/* custom/button.m.css */
.root {
   /* use root class from base theme */
   composes 'root' from '../base/button.m.css'; 
}

.text {
   /* provide new text class */
   color: red;
}
```
