### ISSUE TITLE
Add missing jsdoc for widget theme classes

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#913]
**Bug**

For the widget documentation all the widget theme classes need to be added with JSDOC to ensure that propagate.

Example:

```css
/* Root class of each menu item */
.root {
	background: white;
	padding: 10px;
	border: 1px solid transparent;
	box-sizing: border-box;
	height: 45px;
}

/* Added to selected items */
.selected {
	background: grey;
}

/* Added to active items */
.active {
	border: 1px solid blue;
}

/* Added to disabled items */
.disabled {
	color: grey;
	font-style: italic;
}
```
